# Generated by Django 4.2.17 on 2024-12-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='puzzles.location'),
        ),
        migrations.AddField(
            model_name='category',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='puzzles.competition'),
        ),
        migrations.AddField(
            model_name='category',
            name='parties_registered',
            field=models.ManyToManyField(blank=True, to='puzzles.party'),
        ),
        migrations.AddField(
            model_name='category',
            name='puzzle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='puzzles.puzzle'),
        ),
        migrations.AddField(
            model_name='category',
            name='registers',
            field=models.ManyToManyField(blank=True, to='puzzles.register'),
        ),
    ]
