# Generated by Django 5.1.4 on 2024-12-30 11:36

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(default=8, max_length=2),
            preserve_default=False,
        ),
    ]
