# Generated by Django 5.1.4 on 2025-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_alter_location_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='pending_user',
            new_name='public_awards',
        ),
        migrations.AddField(
            model_name='participant',
            name='public_country',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='public_points',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='public_puzzles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='public_ranking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
