name: puzzle_league
services:
    web-frontend:
        build:
            context: puzzle_league_frontend/
            network: host
        command: npm run dev -- --host
        volumes:
            - .:/workspace:bind
        ports:
            - "5173:5173"

    web-backend:
        build:
            context: puzzle_league_backend/
            network: host
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/workspace:bind
        ports:
            - "8000:8000"