allowBuilds:
  '@prisma/engines': true
  core-js: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - cookie@0.7.0
  - lodash@4.17.23
  - hono@4.11.7
  - hono@4.11.10
  - '@sveltejs/adapter-vercel@6.3.2'
  - hono@4.12.4
  - '@hono/node-server@1.19.10'
  - tar@7.5.10
  - tar@7.5.11
  - hono@4.12.7
  - devalue@5.6.4
  - kysely@0.28.12
  - effect@3.20.0
  - kysely@0.28.14
  - brace-expansion@5.0.5
  - picomatch@4.0.4
  - lodash@4.17.24
  - defu@6.1.5
  - vite@7.3.2
  - hono@4.12.12
  - '@hono/node-server@1.19.13'
  - '@sveltejs/kit@2.57.1'
  - hono@4.12.14
  - postcss@8.5.10
  - hono@4.12.18
  - kysely@0.28.17
  - svelte@5.55.7
  - hono@4.12.16
  - devalue@5.8.1
  - better-auth@1.6.2
  - brace-expansion@5.0.6
  - ws@8.20.1
  - '@sveltejs/kit@2.60.1'
  - uuid@11.1.1
