packages:
  # include packages in subfolders (change as required)
  - 'apps/**'
  - 'packages/**'
  # if required, exclude directories
  - '!**/test/**'
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: false
